"""Config validation test for gbs-auth-platform-b-orders.

GENERATED by `dfx job add` from specs/gbs_auth/platform_b_orders.md — safe to extend with
job-specific assertions; regeneration only overwrites with --force.
"""

from __future__ import annotations

from pathlib import Path

from dbx_rt_ingestion.config.loader import SpecLoader
from dbx_rt_ingestion.config.validation import validate_app_spec

PROJECT_ROOT = Path(__file__).resolve().parents[2]
CONFIG = PROJECT_ROOT / "conf" / "jobs" / "gbs_auth" / "gbs_auth_platform_b_orders.yaml"


def test_gbs_auth_platform_b_orders_config_is_valid() -> None:
    loader = SpecLoader(conf_dir=PROJECT_ROOT / "conf", environment="dev")
    spec = loader.load_app_spec(CONFIG)
    validate_app_spec(spec)
    assert spec.name == "gbs-auth-platform-b-orders"


def test_gbs_auth_platform_b_orders_mappings_resolve() -> None:
    loader = SpecLoader(conf_dir=PROJECT_ROOT / "conf", environment="dev")
    spec = loader.load_app_spec(CONFIG)
    for topic in spec.source.topics:
        if topic.mapping_file:
            assert topic.mapping, f"mapping file of '{topic.name}' produced no columns"
