"""Schema mapping: declarative source-to-target column projection.

Mapping files are the data contract between a source payload and the sink
table. They are authored per schema subject (generated by ``dfx job add``
under ``resources/schemas/<subject>/``) and applied after parsing and quality
checks, on valid records only:

    columns:
      - target: order_id
        source: ord_id
      - target: amount_usd
        expr: "amount * fx_rate"
        type: decimal(18,2)
      - target: status
        source: status_code
        default: "UNKNOWN"

When a topic has a mapping, the output contains exactly the mapped columns
plus the ``_dfx_*`` envelope; when it has none, parsed columns pass through.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

from dbx_rt_ingestion.config.models import ColumnMappingSpec
from dbx_rt_ingestion.core.exceptions import ConfigurationError

if TYPE_CHECKING:  # pragma: no cover
    from pyspark.sql import Column, DataFrame


def _mapped_column(mapping: ColumnMappingSpec) -> Column:
    from pyspark.sql import functions as F

    column = F.expr(mapping.expr) if mapping.expr else F.col(mapping.source or mapping.target)
    if mapping.type:
        column = column.cast(mapping.type)
    if mapping.default is not None:
        column = F.coalesce(column, F.lit(mapping.default))
    return column.alias(mapping.target)


def apply_mapping(df: DataFrame, mapping: list[ColumnMappingSpec]) -> DataFrame:
    """Project the DataFrame to the mapped target columns (+ envelope)."""

    if not mapping:
        return df

    from pyspark.sql import functions as F

    targets = [m.target for m in mapping]
    duplicates = {t for t in targets if targets.count(t) > 1}
    if duplicates:
        raise ConfigurationError(
            "Mapping produces duplicate target columns",
            context={"duplicates": sorted(duplicates)},
        )

    envelope = [F.col(c) for c in df.columns if c.startswith("_dfx_")]
    return df.select(*envelope, *[_mapped_column(m) for m in mapping])
