"""gbs-auth-platform-b-orders — Databricks job entry point (platform_b).

GENERATED by `dfx job add` from specs/gbs_auth/platform_b_orders.md.
Do not edit by hand — update the functional spec and regenerate with --force.

Deployed via Databricks Asset Bundles as a spark_python_task; the runtime
behavior is fully defined by the job config this file points at.
"""

from __future__ import annotations

import argparse

from dbx_rt_ingestion.entrypoint import run_app


def main() -> None:
    parser = argparse.ArgumentParser(prog="gbs-auth-platform-b-orders")
    parser.add_argument("--env", required=True, help="Environment name (dev|qa|prod)")
    parser.add_argument(
        "--config",
        default="conf/jobs/gbs_auth/gbs_auth_platform_b_orders.yaml",
        help="Path to the generated job config",
    )
    parser.add_argument("--conf-dir", default="conf", help="Configuration root")
    args = parser.parse_args()

    run_app(spec_path=args.config, environment=args.env, conf_dir=args.conf_dir)


if __name__ == "__main__":
    main()
